FORMAT: 1A
HOST: http://stg.visikard.com/v36/

# VisiKard

## get Credit Card List [/kashkard/wallet/user/getbalance]

### get list credit card [POST]

+ Request (application/x-www-form-urlencoded)

        fkUser=33287&deviceID=

+ Response 200 (application/json)

    + Headers 
    
            Location: /kashkard/wallet/user/getbalance
            
    + Body
    
            {
              "extend": null,
              "clientMessage": "",
              "status": "OK",
              "statusCode": 200,
              "result": []
            }

## get point [/point/get/point/level/{fkUser}]

+ Parameters
    + fkUser - A path variable that is required for a valid URL

### get point [GET]
+ Response 200 (application/json)

    + Headers 
    
            Location: /kashkard/wallet/user/getbalance
            
    + Body
    
            {
              "extend": null,
              "clientMessage": "",
              "status": "OK",
              "statusCode": 200,
              "result": []
            }

## get Gift Kards By konnect zone [/deal/get/giftKardsByUserAndKonnectzone/{userId}/{konnectZoneId}]

+ Parameters
    + userId - A path variable that is required for a valid URL
    + konnectZoneId - 
    
### get point [GET]
+ Response 200 (application/json)

    + Headers 
    
            Location: /kashkard/wallet/user/getbalance
            
    + Body
    
            {
                "clientMessage": "",
                "extend": null,
                "statusCode": 200,
                "status": "OK",
                "result": [
                    {
                        "cert_value": 95,
                        "purchase_value": 100,
                        "thumb": "http://stg.visikard.com/cache/new/users/34666/gk_image_code_qr_20179171443.png",
                        "img": "http://stg.visikard.com/cache/new/users/34666/gk_image_code_qr_20179171443.png",
                        "currency": "",
                        "name": "KaKaKa",
                        "id": 2284,
                        "type": 1
                    },
                    {
                        "cert_value": 55,
                        "purchase_value": 100,
                        "thumb": "http://stg.visikard.com/cache/new/users/34666/gk_image_code_qr_20179171443.png",
                        "img": "http://stg.visikard.com/cache/new/users/34666/gk_image_code_qr_20179171443.png",
                        "currency": "",
                        "name": "KaKaKa",
                        "id": 2285,
                        "type": 1
                    }
                ]
            }

## Payment [/api/payment/init]

### Init Transaction[POST]

+ Request (application/json)

        {
            "amount" : 2,
            "sessionId":"WK2WGOYDT3D8AHXBDDXC3XM16LJ5VIRU37KONQVT",
            "deviceId" : "D034F820-DCBB-4799-A9CD-B44CBF6901DC",
            "fkUser" : 34665,
            "cvv":"900",
            "groupId" : 538,
            "kashKardToken" : "62843835bca94755ac92851e8d762741",
            "orgAmount" : 12,
            "point" : 0,
            "products":[{
                    "id": "123",
                    "quantity": 1,
                    "price": 5.9
                }],//nullable
            "giftKards": [{
                    "giftKardAmount" : 100,
                    "giftKardId" : 2285,
                    "redeemAmount" : 10,
                    "type":1
                }],//nullable
            "coupon":{
                    "couponId": 123,
                    "percent": 0,
                    "amount": 1.0,
                    "type":1
            }//nullable
        }

+ Response 200 (application/json)

    + Headers 
    
            Location: /api/payment/init
            
    + Body
    
            {
                "clientMessage": "SUCCESS",
                "extend": null,
                "statusCode": 0,
                "status": "OK",
                "result": {
                    "paymentStatus": null,
                    "transactionId": "e78d1805da1c4f71bc9c0c5b70a0d866",
                    "statusCode": "",
                    "invoiceBalance": "2.0",
                    "status": "0"
            }

## get minimum amount [/utils/getminamount]
    
### get minimum amount [GET]
+ Response 200 (application/json)

    + Headers 
    
            Location: /utils/getminamount
            
    + Body
    
            {
              "extend": null,
              "clientMessage": "",
              "status": "OK",
              "statusCode": 200,
              "result": [5.0]
            }

## get maximum percent of point, which user can use [/utils/getmaxpoint]
    
### get maximum percent of point [GET]
+ Response 200 (application/json)

    + Headers 
    
            Location: /utils/getmaxpoint
            
    + Body
    
            {
              "extend": null,
              "clientMessage": "",
              "status": "OK",
              "statusCode": 200,
              "result": 10.0
            }

## get list of option point user can choose [/utils/getpointcfg]
    
### get list of option point choice [GET]
+ Response 200 (application/json)

    + Headers 
    
            Location: /utils/getpointcfg
            
    + Body
    
            {
              "extend": null,
              "clientMessage": "",
              "status": "OK",
              "statusCode": 200,
              "result": [3,5,10]
            }
            

## get Coupon for user by merchant konnect zone [/special/coupon/merchant/user/all]
    
### get Coupon for user by merchant konnect zone [POST]
+ Request (application/x-www-form-urlencoded)

        fkUser=33287&konnecZoneId=1234
        
+ Response 200 (application/json)

    + Headers 
    
            Location: /special/coupon/merchant/user/all
            
    + Body
    
            {
                "extend": null,
                "clientMessage": "",
                "statusCode": 200,
                "status": "OK",
                "result": [
                    {
                        "couponDetailLabel": "[{\"label\":\"30% OFF FOR LUNCH OR DINNERS\",\"value1\":\"30\",\"value2\":\"30\"}]",
                        "type": 0,
                        "fkUser": 33920,
                        "merchantName": "Vy Restaurant",
                        "imageKard": "http://stg.visikard.com/cache/new/users/33920/cp_image_code_qr_201652682838.png",
                        "icons": null,
                        "idCampaignSpecail": 4159,
                        "campaignType": -1,
                        "specailDetail": "30% OFF FOR LUNCH OR DINNERS, IN ONE MONTH",
                        "textImage1": "",
                        "campaignDetail": "30% OFF FOR LUNCH OR DINNERS",
                        "latitude": "",
                        "longitude": "",
                        "isGiftKard": 2,
                        "categoryCard": 1,
                        "fkKard": 7036,
                        "logos": "http://stg.visikard.com/cache/new/images/trophytemplate/33920/thumb_Graphic_33920_201652311822.jpg",
                        "imageSpecial": "http://stg.visikard.com/cache/new/users/33920/cp_image_code_qr_201652682838.png",
                        "textImage2": "",
                        "idCoupon": 5306,
                        "conditions": "",
                        "aboutBusiness": "",
                        "imageShow": "http://stg.visikard.com/cache/new/users/33920/cp_image_code_qr_201652682838.png",
                        "isOffer": 0,
                        "expireDate": "2016-06-30 05:28:39.0",
                        "address": "666 Cách Mạng tháng Tám, phường 5, Ho Chi Minh, Vietnam",
                        "location": [
                            {
                                "optionLocation": "666 Cách Mạng tháng Tám, phường 5, Ho Chi Minh, Vietnam",
                                "latitude": "10.7890767",
                                "longitude": "106.66055119999999"
                            }
                        ]
                    }
                ]
            }

## get payment setting [/utils/paymentsetting]
    
### get payment setting [GET]
+ Response 200 (application/json)

    + Headers 
    
            Location: /utils/paymentsetting
            
    + Body
    
            {
                "clientMessage": "",
                "extend": null,
                "statusCode": 200,
                "status": "OK",
                "result": {
                    "minAmount": 5,
                    "maxPoint": 10,
                    "listChoice": [
                        3,
                        5,
                        10
                    ],
                    "pointRatio": 1000
                }
            }